_BASE_: "../Base_PoseTrack17.yaml"
EXPERIMENT_NAME: 'OTPose_Network_Model_RSN'
WORKERS: 8
GPUS: (0,1,2)
OUTPUT_DIR: './output/PE/DcPose/'
CUDNN:
  BENCHMARK: true
  DETERMINISTIC: true
  ENABLED: true
CORE_FUNCTION: CommonFunction

MODEL:
  NAME: OTPose

  USE_PRF: true
  PRF_BASICBLOCK_NUM: 2
  PRF_INNER_CH: 34

  USE_PTM: true
  PTM_BASICBLOCK_NUM: 1
  PTM_INNER_CH: 17

  USE_PCN: true
  PRF_PTM_COMBINE_BASICBLOCK_NUM: 2
  PRF_PTM_COMBINE_INNER_CH: 64

  DEFORMABLE_CONV:
    DILATION:
      - 3
      - 6
      - 9
      - 12
      - 15
    AGGREGATION_TYPE: weighted_sum
