CUDNN:
  BENCHMARK: false
  DETERMINISTIC: false
  ENABLED: true

WORKERS: 4
PRINT_FREQ: 100
DISTANCE: 2

DATASET:
  NAME: "PoseTrack"
  JSON_DIR: "/media/kyungminjin/47b75869-6a57-4b58-841e-a20a0e7e67d0/OTPose/datasets/PoseTrack/OTPose_supp_files/posetrack17_json_files"
  IMG_DIR: "/media/kyungminjin/47b75869-6a57-4b58-841e-a20a0e7e67d0/OTPose/datasets/PoseTrack/DataSet/PoseTrack2017/images_renamed"
#  TEST_IMG_DIR: "/media/kyungminjin/47b75869-6a57-4b58-841e-a20a0e7e67d0/OTPose/datasets/PoseTrack/DataSet/PoseTrack2017/images_renamed" #test
  TEST_IMG_DIR: "/media/kyungminjin/47b75869-6a57-4b58-841e-a20a0e7e67d0/OTPose/datasets/PoseTrack/DataSet/PoseTrack2017/images" # val
  IS_2018: false
  COLOR_RGB: true
  DATASET: 'posetrack'
  ROOT: ''
  TEST_SET: 'val2017'
  TRAIN_SET: 'train2017'
  # INPUT_TYPE in ['single_frame','spatiotemporal_window']
  INPUT_TYPE: 'spatiotemporal_window'
  BBOX_ENLARGE_FACTOR: 1.0


MODEL:
  FREEZE_HRNET_WEIGHTS: false #
  EVALUATE: true
  INIT_WEIGHTS: true

  NUM_JOINTS: 17
#  PRETRAINED_HRNET: '/media/kyungminjin/47b75869-6a57-4b58-841e-a20a0e7e67d0/OTPose/datasets/PoseTrack/OTPose_supp_files/pretrained_models/pretrained_coco_model.pth'
  PRETRAINED: '/media/kyungminjin/47b75869-6a57-4b58-841e-a20a0e7e67d0/OTPose/datasets/PoseTrack/OTPose_supp_files/pretrained_models/pretrained_coco_model.pth'
#  PRETRAINED: '/media/kyungminjin/47b75869-6a57-4b58-841e-a20a0e7e67d0/OTPose/datasets/PoseTrack/OTPose_supp_files/pretrained_models/DCPose/PoseTrack17_DCPose.pth'
  TARGET_TYPE: gaussian
  IMAGE_SIZE:
    - 288
    - 384
  HEATMAP_SIZE:
    - 72
    - 96
  SIGMA: 3
  USE_RECTIFIER: true

  EXTRA:
    PRETRAINED_LAYERS:
      - '*'
    FINAL_CONV_KERNEL: 1
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
      NUM_CHANNELS:
        - 48
        - 96
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
        - 4
      NUM_CHANNELS:
        - 48
        - 96
        - 192
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
        - 4
        - 4
      NUM_CHANNELS:
        - 48
        - 96
        - 192
        - 384
      FUSE_METHOD: SUM
    DECONV:
      NUM_DECONVS: 1
      NUM_CHANNELS:
        - 48
      KERNEL_SIZE:
        - 4
      NUM_BASIC_BLOCKS: 4
      CAT_OUTPUT:
        - True

TRAIN:
  FLIP: true
  NUM_JOINTS_HALF_BODY: 8
  PROB_HALF_BODY: 0.3
  ROT_FACTOR: 45
  SCALE_FACTOR: [ 0.35,0.35 ]
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 38
  OPTIMIZER: AdamW
  LR: 0.0001
  LR_FACTOR: 0.1
  MILESTONES:
    - 4
    - 8
    - 12
    - 16
  GAMMA: 0.9


  MOMENTUM: 0.9
  NESTEROV: false

VAL:
  ANNOT_DIR: '/media/kyungminjin/47b75869-6a57-4b58-841e-a20a0e7e67d0/OTPose/datasets/PoseTrack/OTPose_supp_files/posetrack17_annotation_dirs/jsons/val/'
  COCO_BBOX_FILE: '/media/kyungminjin/47b75869-6a57-4b58-841e-a20a0e7e67d0/OTPose/datasets/PoseTrack/OTPose_supp_files/posetrack17_precomputed_boxes/val_boxes.json'
  USE_GT_BBOX: true
  BBOX_THRE: 1.0
  IMAGE_THRE: 0.2
  IN_VIS_THRE: 0.2
  NMS_THRE: 1.0
  OKS_THRE: 0.9
  FLIP_VAL: false
  POST_PROCESS: true

TEST:
  ANNOT_DIR: '/media/kyungminjin/47b75869-6a57-4b58-841e-a20a0e7e67d0/STPose/datasets/PoseTrack/OTPose_supp_files/posetrack17_annotation_dirs/jsons/test'
  COCO_BBOX_FILE: '/media/kyungminjin/47b75869-6a57-4b58-841e-a20a0e7e67d0/STPose/datasets/PoseTrack/OTPose_supp_files/posetrack17_precomputed_boxes/test_boxes.json'
  USE_GT_BBOX: false
  BBOX_THRE: 1.0
  IMAGE_THRE: 0.2
  IN_VIS_THRE: 0.2
  NMS_THRE: 1.0
  OKS_THRE: 0.9
  FLIP_TEST: false
  POST_PROCESS: true