WORKERS: 8
PRINT_FREQ: 100
DISTANCE: 2

DATASET:
  NAME: "PoseTrack"
  JSON_DIR: "./datasets/PoseTrack/OTPose_supp_files/posetrack18_json_files"
  IMG_DIR: "./datasets/PoseTrack/DataSet/PoseTrack2018"
  TEST_IMG_DIR: "./datasets/PoseTrack/DataSet/PoseTrack2018"
  IS_2018: true
  COLOR_RGB: true
  DATASET: "posetrack"
  ROOT: ""
  INPUT_TYPE: "spatiotemporal_window"
  BBOX_ENLARGE_FACTOR: 1.25

MODEL:
  FREEZE_HRNET_WEIGHTS: false #true #
  EVALUATE: true
  INIT_WEIGHTS: true
  DEVICE: cuda

  NUM_JOINTS: 17
  PRETRAINED: "./datasets/PoseTrack/OTPose_supp_files/pretrained_models/pretrained_coco_model.pth"
  TARGET_TYPE: gaussian
  IMAGE_SIZE:
    - 288
    - 384
  HEATMAP_SIZE:
    - 72
    - 96
  SIGMA: 3
  USE_RECTIFIER: true

  EXTRA:
    PRETRAINED_LAYERS:
      - "*"
    FINAL_CONV_KERNEL: 1
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
      NUM_CHANNELS:
        - 48
        - 96
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
        - 4
      NUM_CHANNELS:
        - 48
        - 96
        - 192
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
        - 4
        - 4
      NUM_CHANNELS:
        - 48
        - 96
        - 192
        - 384
      FUSE_METHOD: SUM
    DECONV:
      NUM_DECONVS: 1
      NUM_CHANNELS:
        - 48
      KERNEL_SIZE:
        - 4
      NUM_BASIC_BLOCKS: 4
      CAT_OUTPUT:
        - True

TRAIN:
  FLIP: true
  NUM_JOINTS_HALF_BODY: 8
  PROB_HALF_BODY: 0.3
  ROT_FACTOR: 45
  SCALE_FACTOR: [0.35, 0.35]
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 50
  OPTIMIZER: AdamW
  LR: 0.00001 #cos mslr
#  LR_END: 0.00001 #cos
  LR_FACTOR: 0.1
  MILESTONES:
    - 4 #4
    - 8 #8
    - 12 #12
    - 16 #16
  GAMMA: 0.1

  NESTEROV: false

VAL:
  ANNOT_DIR: "./datasets/PoseTrack/OTPose_supp_files/posetrack18_annotation_dirs/val/"
  COCO_BBOX_FILE: "./datasets/PoseTrack/OTPose_supp_files/posetrack18_precomputed_boxes/val_boxes.json"
  USE_GT_BBOX: true
  BBOX_THRE: 1.0
  IMAGE_THRE: 0.1
  IN_VIS_THRE: 0.1
  NMS_THRE: 1.0
  OKS_THRE: 0.9
  FLIP_VAL: false
  POST_PROCESS: true

TEST:
  ANNOT_DIR: "./datasets/PoseTrack/OTPose_supp_files/posetrack18_annotation_dirs/test"
  COCO_BBOX_FILE: "./datasets/PoseTrack/OTPose_supp_files/posetrack18_precomputed_boxes/test_boxes.json"
  USE_GT_BBOX: false
  BBOX_THRE: 1.0
  IMAGE_THRE: 0.1
  IN_VIS_THRE: 0.1
  NMS_THRE: 1.0
  OKS_THRE: 0.9
  FLIP_TEST: false
  POST_PROCESS: true
